var cloudinary = require('cloudinary').v2;

cloudinary.config({
  cloud_name: process.env.CLOUDINARY_CLOUD_NAME, 
  api_key: process.env.CLOUDINARY_API_KEY, 
  api_secret: process.env.CLOUDINARY_API_SECRET,
  secure: true
})
const uploadImage = async (filePath, options) => {
  try {
    // File upload
    const result = await cloudinary.uploader.upload(filePath, { 
      folder: 'zular',
      use_filename: true,
      unique_filename: false,
      ...options
      //async: true
    })
    console.log();
    console.log("** File Upload");
    console.log("* public_id for the uploaded image is generated by Cloudinary's service.");
    console.log("* " + result.public_id);
    console.log("* " + result.url);
    
    return result
  } 
  catch (err) {
    console.error(err);
    return false
  }
}

const deleteImage = async (public_id) => {
  try {
    // Delete
    const result = await cloudinary.uploader.destroy(public_id)
    console.log();
    console.log("** File Deleted");
    console.log(`* file with public_id: ${public_id} has been deleted Cloudinary's service.`);
    
    return result
  } 
  catch (err) {
    console.error(err);
    return false
  }
}

module.exports = {
  uploadImage,
  deleteImage
}